# exp_debug.yaml  —— 最小可运行配置（用于整体流程 debug）

seed: 42

# ======================
# 数据读取（Reader 版本化）
# ======================
data:
  npz_path : "/home/goatoine/Documents/Lanyue/data/data_for_GCN/data_basic_GCN/case1888rte_0504_samples.npz"
  reader: "opf_reg_array" #key_features = ["A_grid", "node_load", "y_cls", "y_arr_reg"]
  adj_mode: "real" #"real";"identity";"random";"random_deg";"nobalmatrix"
  num_workers: 4
  norm: zscore  


train:
  batch_size: 64
  epochs: 200
  lr: 4.0e-3

  # # 下面三项先按需开关；不需要就保留默认
  # amp: false           # 混合精度
  # grad_clip: null      # 例如 1.0
  # accum_steps: 1       # 梯度累积步数

  # # 学习率调度器（先关掉；需要时换成 steplr / cosine）
  scheduler: null
  # scheduler:
  #   name: "steplr"
  #   step_size: 10
  #   gamma: 0.5

  # # 早停（验证指标是 val_mae；不需要就设为 null）
  early_stop: null
  # # early_stop:
  # #   patience: 5
  # #   mode: "min"
  # #   min_delta: 1.0e-4

model:
  name: "gcn_x_appnp"
  hidden: 64          
  x_hidden: 256
  # if use appnp, layers need to be 1, adjust K to control propagation steps      
  layers: 1
  readout: "mean_max"
  out_array_dim: 15
  dropout: 0.2
  K: 2
  alpha: 0.5
  use_ln: false
  num_nodes: 1888

loss:
  name: "arr_mse"


task:
  name: "opf_basicA_task"

evaluator:
  name: "arr_rsm_reg"
  output_dir: "/home/goatoine/Documents/Lanyue/models/GNN/result/May5_chordal_5_2_reg"

logger:
  log_dir: "/home/goatoine/Documents/Lanyue/models/GNN/result/May5_chordal_5_2_reg/log"

checkpoint:
  dir: "/home/goatoine/Documents/Lanyue/models/GNN/checkpoints/0502_gcn_x_3_reg.pth"