seed: 42

data:
  npz_path: "/home/goatoine/Documents/Lanyue/data/data_for_GCN/data_basic_GCN/case2746wop_1118_samples.npz"
  reader: "opf_vA_balance_pointwise_adjmode_highvar_instance"
  adj_mode: "real"
  scheme_dim: 6
  num_workers: 4
  norm: zscore
  highvar_quantile: 0.70
  highvar_topk: null

train:
  batch_size: 64
  epochs: 20
  lr: 4.0e-4
  scheduler: null
  early_stop: null

model:
  name: "mlp_pointwise_flatten"
  hidden: 256
  mlp_layers: 3
  dropout: 0.2
  use_ln: true
  num_nodes: 2746
  out_scalar: true
  out_array_dim: 6

loss:
  name: "scalar_mse"

task:
  name: "opf_basicA_task"

evaluator:
  name: "arr_rsm_runtime"
  output_dir: "/home/goatoine/Documents/Lanyue/models/GNN/result/Feb24_pointwise_mlp_flat_highvar_test"

logger:
  log_dir: "/home/goatoine/Documents/Lanyue/models/GNN/result/Feb24_pointwise_mlp_flat_highvar_test/log"
