seed: 42

data:
  npz_path: "/home/goatoine/Documents/Lanyue/data/data_for_GCN/data_basic_GCN/case2746wop_1118_samples.npz"
  reader: "opf_vA_balance_instancemean_adjmode_highvar"
  adj_mode: "real"
  scheme_dim: 6
  num_workers: 4
  norm: zscore
  highvar_quantile: 0.70
  highvar_topk: null

train:
  batch_size: 32
  epochs: 80
  lr: 1.0e-3
  scheduler: null
  early_stop: null

model:
  name: "linear_pointwise_loadstats"
  out_scalar: true
  out_array_dim: 6

loss:
  name: "scalar_mse"

task:
  name: "opf_basicA_task"

evaluator:
  name: "scalar_reg"
  output_dir: "/home/goatoine/Documents/Lanyue/models/GNN/result/Feb24_instancemean_linear_loadstats_highvar_test"

logger:
  log_dir: "/home/goatoine/Documents/Lanyue/models/GNN/result/Feb24_instancemean_linear_loadstats_highvar_test/log"
